# Generated by Django 4.2.2 on 2023-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0004_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='info',
            field=models.CharField(default=18, max_length=255),
            preserve_default=False,
        ),
    ]
