# Generated by Django 4.2.2 on 2023-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0005_details_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filedetails',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
