# Generated by Django 4.2.2 on 2023-08-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0007_alter_file_filedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filedetails',
            field=models.CharField(max_length=50),
        ),
    ]
